image: python:3.12

pipelines:
  branches:
    main:
      - step:
          name: Lint, Type Check, and Test
          caches:
            - pip
          script:
            - pip install uv
            - uv pip install ".[dev]" --system
            - python -m pylint src/predictr_cli/*.py src/predictr_cli/commands/*.py
            - python -m mypy src/predictr_cli
            - python -m pytest
